/**
 * Custom worker entry point for Cloudflare
 * This file exports Durable Object classes alongside the Next.js app
 */

// Re-export the OpenNext worker handler generated by `opennextjs-cloudflare build`.
// Wrangler will bundle this file (and its deps) as the actual deployed worker.
export { default } from "./.worker-next/index.mjs";
export * from "./.worker-next/index.mjs";

// Export RealtimeActor Durable Object for Cloudflare bindings.
// This keeps the DO class available to Wrangler without forcing OpenNext's build
// step to bundle `@cloudflare/actors` (which imports `cloudflare:workers`).
export { RealtimeActor } from "@ottabase/cf-realtime/server";
