import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { PrismaConfig } from "./types";

// Complete path patterns for easy developer reference
const OTTABASE_CORE_SCHEMA_PATH = "packages/db/prisma/ottabase.schema.prisma";
const DEFAULT_APP_SCHEMA_PATH = "ottabase/prisma/app.schema.prisma";
const PRISMA_CONFIG_PATH = "ottabase/prisma/prisma.config.js";
const DEFAULT_OUTPUT_SCHEMA_PATH = "prisma/schema.prisma";

// Path construction helpers
const getOttabasePrismaDir = (cwd: string) =>
  path.join(cwd, "ottabase", "prisma");
const getPrismaConfigPath = (cwd: string) => path.join(cwd, PRISMA_CONFIG_PATH);
const getAppSchemaPath = (cwd: string, customPath?: string) =>
  path.join(cwd, customPath || DEFAULT_APP_SCHEMA_PATH);
const getOutputSchemaPath = (cwd: string, customPath?: string) =>
  path.join(cwd, customPath || DEFAULT_OUTPUT_SCHEMA_PATH);

// Core schema fallback paths (relative to different starting points)
const getCoreSchemaFallbackPaths = (cwd: string) => [
  // From app directory: ../../packages/db/prisma/ottabase.schema.prisma
  path.join(cwd, "..", "..", OTTABASE_CORE_SCHEMA_PATH),
  // From root directory: packages/db/prisma/ottabase.schema.prisma
  path.join(cwd, OTTABASE_CORE_SCHEMA_PATH),
  // From packages directory: ../db/prisma/ottabase.schema.prisma
  path.join(cwd, "..", "db", "prisma", "ottabase.schema.prisma"),
];

const loadConfig = async (configPath: string): Promise<PrismaConfig> => {
  // Try both .js and .ts extensions
  const jsConfigPath = configPath;
  const tsConfigPath = configPath.replace(".js", ".ts");

  let actualConfigPath = "";
  if (existsSync(jsConfigPath)) {
    actualConfigPath = jsConfigPath;
  } else if (existsSync(tsConfigPath)) {
    actualConfigPath = tsConfigPath;
  } else {
    return { includeOttabaseSchema: true };
  }

  // Simple require-based loading for .js/.ts files or default config
  try {
    const config = require(actualConfigPath);
    return config.default || config;
  } catch {
    return { includeOttabaseSchema: true };
  }
};

const getCoreSchemaPath = (): string => {
  // Find the @ottabase/db package and get its schema
  try {
    // First try to resolve from current working directory
    const dbPackagePath = require.resolve("@ottabase/db/package.json");
    const dbDir = path.dirname(dbPackagePath);
    return path.join(dbDir, "prisma", "ottabase.schema.prisma");
  } catch {
    // Fallback: try to find it in the monorepo structure
    const cwd = process.cwd();
    const possiblePaths = getCoreSchemaFallbackPaths(cwd);

    for (const schemaPath of possiblePaths) {
      if (existsSync(schemaPath)) {
        return schemaPath;
      }
    }

    throw new Error(
      "Could not find @ottabase/db package. Make sure it is installed.",
    );
  }
};

const runPrismaGenerate = async (
  schemaPath: string,
  cwd: string,
): Promise<void> => {
  return new Promise((resolve, reject) => {
    const child = spawn("npx", ["prisma", "generate", "--schema", schemaPath], {
      cwd,
      stdio: "inherit",
      shell: true,
    });

    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`Prisma generate exited with code ${code}`));
      }
    });
  });
};

export const concatenatePrismaSchema = async (
  cwd: string = process.cwd(),
): Promise<void> => {
  const prismaDir = getOttabasePrismaDir(cwd);
  const configPath = getPrismaConfigPath(cwd);

  // Load configuration
  const config = await loadConfig(configPath);

  // Define paths
  const appSchemaPath = getAppSchemaPath(cwd, config.appSchemaPath);
  const outputSchemaPath = getOutputSchemaPath(cwd, config.outputSchemaPath);

  const schemas: string[] = [];

  // Add core schema if enabled
  if (config.includeOttabaseSchema !== false) {
    try {
      const coreSchemaPath = getCoreSchemaPath();
      const coreSchema = await readFile(coreSchemaPath, "utf8");
      schemas.push(`// ---- Core Schema ----\n${coreSchema.trim()}`);
    } catch (error) {
      console.warn(
        "Warning: Could not load core schema:",
        (error as Error).message,
      );
    }
  }

  // Add app schema if it exists
  if (existsSync(appSchemaPath)) {
    const appSchema = await readFile(appSchemaPath, "utf8");
    schemas.push(`// ---- App Schema ----\n${appSchema.trim()}`);
  }

  if (schemas.length === 0) {
    throw new Error("No schemas found to concatenate");
  }

  // Create combined schema
  const timestamp = new Date().toLocaleString();
  const header =
    "// This file is auto-generated by @ottabase/scripts\n// Do not edit this file directly\n" +
    `// Script generated at: ${timestamp}\n`;
  const combinedSchema = header + "\n" + schemas.join("\n\n") + "\n";

  // Ensure output directory exists
  const outputDir = path.dirname(outputSchemaPath);
  await mkdir(outputDir, { recursive: true });

  // Write combined schema
  await writeFile(outputSchemaPath, combinedSchema, "utf8");

  console.log(`✅ Generated schema at ${outputSchemaPath}`);

  // Run prisma generate
  await runPrismaGenerate(outputSchemaPath, cwd);

  console.log("✅ Prisma client generated successfully");
};
